### ISSUE TITLE
OS X error 

### ISSUE THREAD

**Issue by robooo** [iCHAIT/moviemon#13]
basic install on mac yosemite and ended with this:

```
$ moviemon /Users/roboo/Movies/
Traceback (most recent call last):
  File "/usr/local/bin/moviemon", line 9, in <module>
    load_entry_point('moviemon==1.0.11', 'console_scripts', 'moviemon')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/moviemon/__init__.py", line 1, in <module>
    from .moviemon import main
  File "/Library/Python/2.7/site-packages/moviemon/moviemon.py", line 32, in <module>
    from guessit import guess_file_info
  File "/Library/Python/2.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/Library/Python/2.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/Library/Python/2.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/Library/Python/2.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/Library/Python/2.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/Library/Python/2.7/site-packages/stevedore/extension.py", line 252, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found
```

**Comment by LluisFelip** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/moviemon", line 7, in <module>
    from moviemon import main
  File "/usr/local/lib/python2.7/site-packages/moviemon/__init__.py", line 1, in <module>
    from .moviemon import main
  File "/usr/local/lib/python2.7/site-packages/moviemon/moviemon.py", line 32, in <module>
    from guessit import guess_file_info
  File "/usr/local/lib/python2.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/usr/local/lib/python2.7/site-packages/stevedore/extension.py", line 261, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found

**Comment by toxygen** [comment]
see https://github.com/iCHAIT/moviemon/issues/14#issuecomment-727226963
