### ISSUE TITLE
stevefore.exception.NoMatches: No guessit.transformer extensions found

### ISSUE THREAD

**Issue by pawamoy** [iCHAIT/moviemon#14]
```console
$ moviemon
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/moviemon", line 5, in <module>
    from moviemon import main
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/moviemon/__init__.py", line 1, in <module>
    from .moviemon import main
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/moviemon/moviemon.py", line 32, in <module>
    from guessit import guess_file_info
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/home/pawamoy/.local/pipx/venvs/moviemon/lib/python3.7/site-packages/stevedore/extension.py", line 261, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found
```

Maybe a Python version compatibility issue? Using Python 3.7.4 here. Installed with `pipx` (the new `pipsi`).

**Comment by pawamoy** [comment]
Not interested anymore, feel free to reopen!

**Comment by Jatin-8898** [comment]
I'm facing the same issue.

**Comment by toxygen** [comment]
this fixes it:
`pip install stevedore==1.19.1`

more info here: https://askubuntu.com/questions/698633/subliminal-does-not-work-in-ubuntu-18-04

**Comment by pawamoy** [comment]
Thanks for the workaround @toxygen, I'll close now since I don't think it will be fixed :slightly_smiling_face:
